### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by happyTonakai** [JamesHoi/Open163-Downloader#1]
在选择字幕是否与影片一起下载后，一闪而过一个报错信息如下

<img width="932" alt="批注 2020-05-07 080002" src="https://user-images.githubusercontent.com/21305646/81240131-21091380-9039-11ea-803a-3cf17036f132.png">

**Comment by JamesHoi** [comment]
你是直接用代码运行，还是直接用exe软件？
我项目里面用的是79版本的chromedriver，可能你替换了我项目中的chromedriver导致了版本问题错误。

**Comment by happyTonakai** [comment]
我直接运行的 exe 文件
这个还需要依赖 Chrome 吗，我的 Chrome 版本是81.0.4044.138，另外我还安装了 Edge Chromium 81.0.416.72

**Comment by JamesHoi** [comment]
其实是需要chrome的，但我打包的exe当中其实包含了chrome，是79的。
我测试也出现了问题，晚上有空我改改，感谢你的反馈

**Comment by JamesHoi** [comment]
已更新版本，[Release v1.1.1](https://github.com/JamesHoi/Open163-Downloader/releases/tag/1.1.1)
原来driver是完全依赖浏览器的，所以假如与电脑上的浏览器版本不匹配则会报错误，这个问题我还在寻找解决方案
