### ISSUE TITLE
ChromeDriver 驱动貌似版本不对哦

### ISSUE THREAD

**Issue by jnsday** [JamesHoi/Open163-Downloader#2]
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 79
直接用的打包好的exe执行文件，执行有报错，应该是打包的 驱动不对

**Comment by JamesHoi** [comment]
问题已解决，请用hotfix版本v1.1.1
https://github.com/JamesHoi/Open163-Downloader/releases/tag/1.1.1

**Comment by JamesHoi** [comment]
貌似网易公开课链接格式已改变，目前软件应该无法正常使用，我有时间我会修改一下的

**Comment by jnsday** [comment]
好的，我看到留言了~~
