### ISSUE TITLE
chromedriver存在版本问题

### ISSUE THREAD

**Issue by juqkai** [JamesHoi/Open163-Downloader#4]
我安装的chrome不是正常的chrome，所以在默认路径下是找不到chrome.exe的，这就导致无法找到chrome.exe。
所以需要指定：``` opt.binary_location=“” ````
同时，我电脑上使用的是80版本的chrome.exe，所以，需要下载对应版本的chromedriver。
去的这里下载的
http://npm.taobao.org/mirrors/chromedriver/

所以觉得可以添加一个变量，放chrome.exe的位置，然后根据chrome.exe的版本自动从这里去下载对应的chromedriver

**Comment by JamesHoi** [comment]
是的，就有人是这样做的，参考这个[webdriver-manager](https://github.com/SergeyPirogov/webdriver_manager)
但我在使用这个库的时候经常有问题...

**Comment by JamesHoi** [comment]
我没啥时间更新这个项目[掩面]，我找到了不用chromedriver就能获取下载链接的方式
例如这个视频 [视频链接](http://open.163.com/newview/movie/courseintro?newurl=MFHCKB983)
其影片信息链接为 [这个](https://c.open.163.com/open/mob/movie/list.do?plid=MFHCKB983)
然后可以解析json获取影片的下载链接以及字幕

**Comment by JamesHoi** [comment]
目前已将selenium改为requests，不需要再考虑chromedriver版本问题
[新版本下载v1.2.0](https://github.com/JamesHoi/Open163-Downloader/releases/tag/v1.2.0)
